baseURL = "/"
title = "Alexander Clines"
languageCode = "en-us"

theme = "hugo-profile"

disableKinds = ["taxonomy", "term"]

[params]
  subtitle = "Software Engineering Manager"
  # Basic profile
  [params.profile]
    name = "Alexander Clines"
    tagline = "Building high-performing teams and on-device NLP."
    avatar = "images/about/user-picture.png"

  # Social links (icons depend on theme’s set)
  [[params.social]]
    icon = "email"
    url = "mailto:me@alexanderclines.com"
  [[params.social]]
    icon = "linkedin"
    url = "https://www.linkedin.com/in/alexander-clines/"

# Menus
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Skills"
    url = "/skills/"
    weight = 3
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 4
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 5

# Optional: enable modules (module-based theme install)
[module]
  [[module.imports]]
    path = "github.com/gurusabarish/hugo-profile"
